---
title: "Dashboard"

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(forcats)
library(rnoaa)
library(lubridate)
```

Column {data-width=650}
-----------------------------------------------------------------------

### The trend of maximum temperature over the years

```{r}
set.seed(1)

data("ny_noaa")

noaa <- ny_noaa %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmax = tmax/10,
    tmin = as.numeric(tmin),
    tmin = as.numeric(tmin),
    tmin = tmin/10,
    prcp = prcp/10
  ) %>% 
  filter(!is.na(tmax) & !is.na(tmin)) %>% 
  mutate(
    year = year(as.Date(date,"%Y/%m/%d")),
    month = month(as.Date(date, "%Y/%m/%d"))
  ) %>% 
sample_n(5000)

p1_y <- list(
  title = 'Average maximum temperature'
)

p1_x <- list(
  title = 'Year'
)

noaa %>% 
  group_by(year) %>% 
  summarize(mean_tmax = mean(tmax)) %>% 
  mutate(
    mean_tmax = round(mean_tmax, digits = 2),
    text_label = str_c("Year: ", year, "\nMaximum temperature: ", mean_tmax
                       )) %>% 
  plot_ly(x = ~year, y = ~mean_tmax, type = "scatter", mode = "lines", 
          text = ~text_label) %>% 
  layout(yaxis = p1_y)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Average temperature by month

```{r}

p2_y <- list(
  title = 'Average temperature'
)

noaa %>% 
  mutate(average_temperature = (tmax + tmin)/2) %>% 
  group_by(month) %>% 
  summarize(mean_temp = mean(average_temperature)) %>% 
  mutate(
    mean_temp = round(mean_temp, digits = 2),
    text_label = str_c('month: ', month, '\nAverage temperature: ', mean_temp)
  ) %>% 
  plot_ly(x = ~month, y = ~mean_temp, type = 'bar', text = ~text_label) %>% 
  layout(yaxis = p2_y)

```

### The distribution of maximal and minimal temperature across stations

```{r}

p3 <- noaa %>%
  select(id, tmax, tmin) %>% 
  gather(key = observation, value = temp, tmax:tmin) %>% 
  ggplot(aes(x = temp, fill = observation)) + geom_density(alpha = .5) +
  theme_bw()
  
ggplotly(p3)

```

